# Generated by Django 6.0.1 on 2026-01-14 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0002_historicalrequest_historicalservice'),
    ]

    operations = [
        # Сначала удаляем связь ManyToMany
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        # Удаляем модели Role и UserRole
        migrations.DeleteModel(
            name='UserRole',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
        # Добавляем новое поле role в User
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Пользователь'), ('admin', 'Администратор')], default='user', max_length=20, verbose_name='Роль'),
        ),
    ]
