# Generated by Django 6.0.1 on 2026-01-14 09:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0003_remove_role_userrole'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrequest',
            name='office',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='mfc.mfcoffice', verbose_name='Отделение МФЦ'),
        ),
        migrations.AddField(
            model_name='request',
            name='office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='mfc.mfcoffice', verbose_name='Отделение МФЦ'),
        ),
    ]
