# Generated by Django 6.0.1 on 2026-01-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mfc', '0004_add_office_to_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='offices',
            field=models.ManyToManyField(blank=True, help_text='Отделения, где предоставляется данная услуга', related_name='services', to='mfc.mfcoffice', verbose_name='Отделения МФЦ'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.ImageField(help_text='Загрузите изображение (JPG, PNG, GIF)', upload_to='documents/%Y/%m/%d/', verbose_name='Файл (изображение)'),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('image', 'Изображение'), ('pdf', 'PDF'), ('other', 'Другое')], default='image', max_length=20, verbose_name='Тип файла'),
        ),
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
